# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-yml.html
spring:
  thymeleaf:
    cache: false
  main:
    show-banner: true
  h2:
    console:
      enabled: true
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG